schemas:
  bootstrap: 8000
  bot_custom: 8000
favicon:
  mimetype: image/png
  path: 'public://favicon-da.png'
  url: 'https://dev-diffabled8.pantheonsite.io/sites/default/files/favicon-da.png'
  use_default: false
logo:
  path: 'public://logo-full.png'
  url: ''
  use_default: false
table_responsive: '-1'
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content_top: ''
  content: ''
  content_bottom: ''
  content_baseline: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
  footer_one: ''
  footer_two: ''
  footer_three: ''
  footer_four: ''
  footer_abs_bottom: ''
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
breadcrumb_home: 1
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
fluid_container: 1
