id: ds_main_navigation
label: 'DS Main Navigation'
ui_limit: page
properties:
  block: 'system_menu_block:main'
  use_block_title: false
  add_block_wrappers: false
type: block
type_label: 'Block field'
entities:
  node: node
